### ISSUE TITLE
Add select / checkbox for regions

### ISSUE THREAD

**Issue by justgook** [marcrobledo/retroarch-playlist-editor#4]
For example I would like split games by playlist for each region ( Europe / USA/ japan)

Other solution would be create custom priority of removing dupes, for example I would like have first Europe, if exist, then USA, and only then JP, now it takes what first found

**Comment by justgook** [comment]
Or even better, when you remove duplicates, leave user choose which of list items should be left, like selectbox for each item

**Comment by marcrobledo** [comment]
I'm implementing a filter function so you type 'Europe' and it selects all content matching that search pattern, then you can do decide what to do with them or even check/uncheck more content.

**Comment by marcrobledo** [comment]
cf017c2bd4be8054f3aec2bc8798302a6ff8ee1e added a new feature that could be a solution for this issue.

Tweak playlist lets you:
* sort content by name (since now user can sort manually content)
* **filter content**
* replace content name massively

Filter content will select automatically content that matches a pattern (which can be a simple text string or a more complex regular expression) user will type.
For example: pattern=" \\(.\*?Japan.\*?\\)" would select all Japan content.

Let me know if it works for you and if you have any suggestion on how to improve it. Any feedback will be appreciated!
